name: Upload and publish python package
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Test Pipeline
    steps:
      run: |
        echo github.event.base_ref
    if: github.event.base_ref == 'refs/heads/main'
    name: Upload Release Asset and publish to Pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install .
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install wheel
      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir polly-python-code/dist/
          
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        
      - name: Check tag output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
          
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload tar.gz
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./polly-python-code/dist/polly-python-${{ steps.vars.outputs.tag }}.tar.gz
          asset_name: polly-python-${{ steps.vars.outputs.tag }}.tar.gz
          asset_content_type: application/octet-stream
          
      - name: Upload whl
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./polly-python-code/dist/polly_python-${{ steps.vars.outputs.tag }}-py3-none-any.whl
          asset_name: polly_python-${{ steps.vars.outputs.tag }}-py3-none-any.whl
          asset_content_type: application/octet-stream
          
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PIPY_TOKEN }}
          packages_dir: ./polly-python-code/dist
    
    
    
