name: Build Python Package

on:
  push:
    branches:
      # regex not supported in github actions
      # - 'release\-[v][0-9\.]+|release\_[v][0-9\.]+'
      - 'release**'
      - ftr_automating_whl_file_creation


jobs:
  build:
    name: Build Python Package on merge to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install .
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install wheel

      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir polly-python-code/dist/
          
      - name: Set output
        id: vars
        run: echo ::set-output name=branch::${GITHUB_REF#refs/*/}
        
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.branch }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.branch }}
          
      # - name: Get release
      #   id: get_release
      #   uses: bruceadams/get-release@v1.2.3
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      
      # - name: Output of get release step
      #   run:  |
      #     echo ${{ steps.get_release.outputs.upload_url }}