name: Build Python Package

on:
  push:
    branches:
      # regex not supported in github actions
      # - 'release\-[v][0-9\.]+|release\_[v][0-9\.]+'
      - 'release**'
      - ftr_automating_whl_file_creation


jobs:
  build:
    name: Build Python Package on merge to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install .
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install wheel
      
      - name: Current Branch Name
        run: |
          echo ${GITHUB_REF#refs/*/}

      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir polly-python-code/dist/

      - name: List files inside dist
        run: |
          cd polly-python-code/dist/
          ls

      # - name: Upload whl to public assets
      #   uses: dmnemec/copy_file_to_another_repo_action@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source_file: 'polly-python-code/dist/polly_python-${GITHUB_REF#refs/*/}-py3-none-any.whl'
      #     destination_repo: 'dmnemec/release-test'
      #     destination_folder: 'test-dir'
      #     user_email: 'example@email.com'
      #     user_name: 'dmnemec'
      #     commit_message: 'A custom message for the commit'
