name: Build Python Package

on:
  push:
    branches:
      # regex not supported in github actions
      # - 'release\-[v][0-9\.]+|release\_[v][0-9\.]+'
      - 'release**'
      - ftr_automating_whl_file_creation


jobs:
  build:
    name: Build Python Package on merge to release
    runs-on: ubuntu-latest
    env:
      version: "0.0.7"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install .
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install wheel
      
      - name: Current Branch Name
        run: |
          echo ${GITHUB_REF#refs/*/}

      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir polly-python-code/dist/

      - name: List files inside dist
        run: |
          cd polly-python-code/dist/
          ls

      - name: Encode whl file and upload it to public assets
        run:  |
          base64 --version
          export WHL_BASE64="$(base64 polly-python-code/dist/polly_python-$version-py3-none-any.whl)"
          echo $WHL_BASE64
          echo ${{ secrets.UPLOAD_TOKEN }}
          export WHL_UPLOAD_PATH="builds/polly-python"
          echo $WHL_UPLOAD_PATH
          sudo apt-get update
          sudo apt install curl
          curl --version
          curl -i -u ${{secrets.UPLOAD_USER_NAME}}:${{ secrets.UPLOAD_TOKEN }} \
          -X PUT \
          -d '{"message":"Uploading whl file","content":"$WHL_BASE64"}' \
          https://api.github.com/repos/ElucidataInc/PublicAssets/contents/$WHL_UPLOAD_PATH \
          

