name: Upload Python Package

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install .
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install wheel
      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir polly-python-code/dist/
      - name: list of dir
        run: ls -R
      - uses: actions/upload-artifact@v2
        with:
          path: ./polly-python-code/dist
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PIPY_TOKEN }}
          packages_dir: ./polly-python-code/dist
          
