name: Unit tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      test_environment: "test"
      test_baseApi: "https://api.testpolly.elucidata.io"
      test_baseV2Api: "https://v2.api.testpolly.elucidata.io"
      test_dockerDomain: "docker.testpolly.elucidata.io"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python and nodejs
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install refreseh_token from polly CLI as Environment Variable
      run: |
        npm --version 
        node --version
        sudo apt-get install -y jq
        sudo apt install moreutils
        npm install -g @elucidatainc/pollycli
        sudo apt-get install expect
        export POLLY_USER_NAME=${{ secrets.POLLY_USER_NAME }}
        export POLLY_USER_PASSWORD=${{ secrets.POLLY_USER_PASSWORD }}
        echo '#!/usr/bin/expect -f' > login.sh
        echo 'set timeout -1' >> login.sh
        echo 'spawn polly login' >> login.sh
        echo 'expect "Enter user name:"' >> login.sh
        echo 'send -- "$env(POLLY_USER_NAME)\r"' >> login.sh
        echo 'expect "Enter password:"' >> login.sh
        echo 'send -- "$env(POLLY_USER_PASSWORD)\n"' >> login.sh
        echo 'spawn polly logout' >> login.sh
        echo 'expect eof' >> login.sh
        chmod +x ./login.sh
        ./login.sh
        temp=$(cat ~/.config/pollycli/credentials.json | jq .$(cat ~/.config/pollycli/credentials.json | jq .pollyUser.pollyemail).pollyrefreshToken)
        temp="${temp%\"}"
        export POLLY_REFRESH_TOKEN="${temp#\"}"
        echo "$POLLY_REFRESH_TOKEN"
        echo -n "$POLLY_REFRESH_TOKEN" | wc -c
        echo "::set-env name=POLLY_REFRESH_TOKEN::${POLLY_REFRESH_TOKEN}"
        echo 'done'
        export global_npm_path=`npm list -g | head -1`
        echo "$global_npm_path"
        sudo cat $global_npm_path/node_modules/@elucidatainc/pollycli/src/env.json | sudo jq \
        --arg env "$test_environment" \
        --arg base_api "$test_baseApi" \
        --arg base_V2api "$test_baseV2Api" \
        --arg dockerDomain "$test_dockerDomain" \
        '.environment|= $env | .baseApi |= $base_api | .baseV2Api |= $base_V2api | 
        .dockerDomain |= $dockerDomain' | sudo sponge \
        $global_npm_path/node_modules/@elucidatainc/pollycli/src/env.json
        echo 'updation of json file done with test polly variables'
        cat $global_npm_path/node_modules/@elucidatainc/pollycli/src/env.json
        export TEST_POLLY_USER_NAME=${{ secrets.TEST_POLLY_USER_NAME }}
        export TEST_POLLY_USER_PASSWORD=${{ secrets.TEST_POLLY_PASSWORD }}
        echo "$TEST_POLLY_USER_NAME"
        echo "$TEST_POLLY_USER_PASSWORD"
        echo '#!/usr/bin/expect -f' > testlogin.sh
        echo 'set timeout -1' >> testlogin.sh
        echo 'spawn polly login' >> testlogin.sh
        echo 'expect "Enter user name:"' >> testlogin.sh
        echo 'send -- "$env(TEST_POLLY_USER_NAME)\r"' >> testlogin.sh
        echo 'expect "Enter password:"' >> login.sh
        echo 'send -- "$env(TEST_POLLY_USER_PASSWORD)\n"' >> testlogin.sh
        echo 'expect eof' >> testlogin.sh
        chmod +x ./testlogin.sh
        ./testlogin.sh
        temp=$(cat ~/.config/pollycli/credentials.json | jq .$(cat ~/.config/pollycli/credentials.json | jq .pollyUser.pollyemail).pollyrefreshToken)
        temp="${temp%\"}"
        export TEST_POLLY_REFRESH_TOKEN="${temp#\"}"
        echo "$TEST_POLLY_REFRESH_TOKEN"
        echo -n "$TEST_POLLY_REFRESH_TOKEN" | wc -c
        echo "::set-env name=TEST_POLLY_REFRESH_TOKEN::${TEST_POLLY_REFRESH_TOKEN}"
        echo 'done'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest tests/
